In [2]:
# Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:

import numpy as np;

arr=np.array([1,2,3,4,5])

# a) Addition of 2 in all the element
print(arr+2)

# b) Multiply 3 with all the elements
print(arr*3)

# c) Divide every element by 2
print(arr/2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [8]:
# Q.2 Questions on Basic NumPy Array:
# a)	Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

arr=np.array([1,2,3,6,4,5])

reversearr=arr[::-1]
print(reversearr)

# b)	Find the most frequent value and their indice(s) in the following arrays:
# i. x = np.array([1,2,3,4,5,1,2,1,1,1]) ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

x = np.array([1,2,3,4,5,1,2,1,1,1])
mfreqx= np.bincount(x)
print(mfreqx.argmax())
indicesx=np.where(x== mfreqx.argmax())
print(indicesx[0])

y = np.array([1,1,1,2,3,4,2,4,3,3])
mfreqy= np.bincount(y)
print(mfreqy.argmax())
indicesy=np.where(y== mfreqy.argmax())
print(indicesy[0])


[5 4 6 3 2 1]
1
[0 5 7 8 9]
1
[0 1 2]


In [9]:
# Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
# a)	Access 1st row, 2nd column
# b)	Access 3rd row, 1st column

arr=np.array([[10,20,30],[40,50,60],[70,80,90]])

print(arr[0,1])
print(arr[2,0])

20
70


In [ ]:
# Q.4 Write program to create an 1-D NumPy array named <> with evenly spaced 25 numbers from 10 to 100 using linspace().
# Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array.
# Find the transpose of this array using reshape() attribute.
# Can we do the same with T attribute?

DakshJain=np.linspace(10,100,num=25)
print(DakshJain)

print(DakshJain.shape)

print(DakshJain.size)

print(DakshJain.dtype)

print(DakshJain.nbytes)

print(DakshJain.reshape(DakshJain.size,1))

arrtranspose= DakshJain.T
print(arrtranspose)





[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [17]:
# Q5. Create a 2-D Array of three rows and four columns, named ucs420_> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35.
# Compute the mean, median, max, min, unique elements.
# Reshape the array to four rows and three columns and name it as reshaped_ ucs420_>.
# Resize the array to two rows and three columns and name it as resized_ ucs420_>.


matrix=np.array([10,20,30,40,50,60,70,70,90,15,20,35])

ucs420_dakshjain= matrix.reshape(3,4)
Elmean=np.mean(ucs420_dakshjain)
print(Elmean)

Elmedian=np.median(ucs420_dakshjain)
print(Elmedian)

maximum=np.max(ucs420_dakshjain)
print(maximum)

minimum=np.min(ucs420_dakshjain)
print(minimum)

uniqueel=np.unique(ucs420_dakshjain)
print(uniqueel)

reshaped_ucs420_dakshjain=ucs420_dakshjain.reshape(4,3)
print(reshaped_ucs420_dakshjain)

resized_ucs420_dakshjain=np.resize(ucs420_dakshjain,(2,3))
print(resized_ucs420_dakshjain)

42.5
37.5
90
10
[10 15 20 30 35 40 50 60 70 90]
[[10 20 30]
 [40 50 60]
 [70 70 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
